---
- name: How to prompt for variables
  hosts: localhost
  gather_facts: no

  vars_prompt:
   - name: "yourpassword" # variable name to define
     prompt: "What is yoour password?" # question to ask
     ## private option use to not reveal the password
     private: yes
     ## run this encription method (optional)
     encrypt: "sha512_crypt"
     ## type the password twice (optional)
     confirm: yes
     ## this is the size of the RAND you'd like to have generated (optional)
     salt_size: 7
     # salt: slappysquirrel88 # provided your own RAND optional
     ## default to this password (optional) 
     default: "qwerty"
  tasks: 
   - name: Print out the password
     debug: 
       msg: "{{ yourpassword }}"
